# OSPlus Disk Imager 1.0 Makefile
.AUTODEPEND


#
# Borland C++ tools and paths
#
IMPLIB  = IMPLIB
BCCDOS  = BCC +BCCDOS.CFG
TLINK   = TLIMK
TLIB    = TLIB
TASM    = TASM

BCPATH  = D:\BC45

#
# IDE macros
#


#
# Options
#
IDE_LFLAGSDOS =  -L$(BCPATH)\LIB
IDE_BFLAGS = 
LLATDOS_dskimagedexe =  -L$(BCPATH)\LIB;$(BCPATH)\LIB -P=65535 -c -Tde
RLATDOS_dskimagedexe = 
BLATDOS_dskimagedexe = 
CNIEAT_dskimagedexe = -I$(BCPATH)\INCLUDE;$(BCPATH)\INCLUDE -D
LNIEAT_dskimagedexe = -x
LEAT_dskimagedexe = $(LLATDOS_dskimagedexe)
REAT_dskimagedexe = $(RLATDOS_dskimagedexe)
BEAT_dskimagedexe = $(BLATDOS_dskimagedexe)

#
# Dependency List
#
Dep_dskimage = \
   dskimage.exe

dskimage : BccDos.cfg $(Dep_dskimage)
  echo MakeNode 

Dep_dskimagedexe = \
   write.obj\
   dskimage.obj

dskimage.exe : $(Dep_dskimagedexe)
  $(TLINK)   @&&|
 /v $(IDE_LFLAGSDOS) $(LEAT_dskimagedexe) $(LNIEAT_dskimagedexe) +
$(BCPATH)\LIB\c0l.obj+
write.obj+
dskimage.obj
$<,$*
$(BCPATH)\LIB\tv.lib+
$(BCPATH)\LIB\cl.lib

|

write.obj :  write.cpp
  $(BCCDOS) -c @&&|
 $(CEAT_dskimagedexe) $(CNIEAT_dskimagedexe) -o$@ write.cpp
|

dskimage.obj :  dskimage.cpp
  $(BCCDOS) -c @&&|
 $(CEAT_dskimagedexe) $(CNIEAT_dskimagedexe) -o$@ dskimage.cpp
|

# Compiler configuration file
BccDos.cfg : 
   Copy &&|
-W-
-R
-v
-vi
-H
-H=dskimage.csm
-v-
-R-
-k-
-ml
-f-
| $@


